version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: etl_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: